# Generated by Django 4.1.5 on 2024-04-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_horasextras_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('id_sonda_plus', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=11)),
                ('nombre_colaborador', models.CharField(max_length=70)),
                ('monto', models.IntegerField()),
                ('cantidad_horas', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('centro_costos', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorasCompensadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('id_sonda_plus', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=11)),
                ('nombre_colaborador', models.CharField(max_length=70)),
                ('monto', models.IntegerField()),
                ('cantidad_horas', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, max_length=3, null=True)),
                ('centro_costos', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(max_length=15)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
