# Generated by Django 4.1.5 on 2024-04-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_disponibilidad_horascompensadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horascompensadas',
            name='concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='horasextras',
            name='concepto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
