# Generated by Django 4.1.5 on 2024-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_disponibilidad_concepto_horascompensadas_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasextras',
            name='numero_documento',
            field=models.CharField(max_length=30),
        ),
    ]
