# Generated by Django 4.1.5 on 2024-04-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_horasextras_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horasextras',
            name='codigo',
        ),
    ]
