# Generated by Django 4.1.5 on 2024-04-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_horasextras_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='horascompensadas',
            name='codigo',
        ),
    ]
