# Generated by Django 4.1.5 on 2024-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_disponibilidad_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('empresa', models.CharField(max_length=20)),
                ('id_sonda_plus', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=25)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(max_length=25)),
                ('centro_costos', models.CharField(max_length=25)),
                ('cantidad_dias', models.IntegerField()),
                ('saldo_monto', models.IntegerField()),
                ('moneda', models.CharField(max_length=3)),
            ],
        ),
    ]
